### ISSUE TITLE
Use README.md

### ISSUE THREAD

**Issue by biinniit** [reuben54/32smiles#4]
Transfer the entire description written in [Our website info.txt](/reuben54/32smiles/blob/main/Our%20website%20info.txt) into [README.md](/reuben54/32smiles/blob/main/README.md), and [learn about using Markdown](https://guides.github.com/features/mastering-markdown/) to structure it properly.

**Comment by reuben54** [comment]
The issue concerning the txt file  Our website info.txt is a temporary document which is not part of the project. It will be deleted from the project.
